FROM node:alpine

COPY . /2b_docker
CMD node /2b_docker/index.js


# replace "2b_docker" with your folder name in both lines if you change it, 
# and make sure to have index.js in that folder as well.